var data = [
{id: 1, quote:"She wasn't born this way. She must have gone dark.", followUp: "Whatever happened to love?", context: "Discussing a lawyer he met on his first day at work. She said that in New York, as a guy there was always someone hotter you could date. As a woman, there was always someone richer."},
{id: 2, quote:"I will be envious of homeless people.", followUp: null, context: "Because he would have negative money--law school loans--and homeless peple would have 0. This was during a pre-lecture jobs pep talk."},
{id: 3, quote:"She wasn't born this way She must have gone dark.", followUp: "Whatever happened to love?", context: "Discussing a lawyer he met on his first day at work. She said that in New York, as a guy there was always someone hotter you could date. As a woman, there was always someone richer."},
{id: 4, quote:"Oh, one more thing.", followUp: "(mutters to self) famous last words", context: "Some lecture, don't remember which one."},
{id: 5, quote:"This place has turned into pure chaos.", followUp: null, context: "Kicking the slowly deflating large balloon from the last cohort's graduation away from him as he began lecture."},
{id: 6, quote:"Who knows what you'll see out there?", followUp: null, context: "About JavaScript and codebases in the real world."},
{id: 7, quote:"I was going to say something was 'aw-ry'", followUp: null, context: "Jeffers throwing back to the first time he mispronounced the word 'awry.'"},
{id: 8, quote:"At that point it zips through the wires.", followUp: null, context: "The technical explanation of the request response cycle."},
{id: 9, quote:"I'm pretty confident it will work.", followUp:  "(mutters to self) Pride comes before the fall.", context:"Just another lecture."},
{id: 10, quote:"True that.", followUp: null, context:"Just Jeff being Jeff."},
{id: 11, quote:"Oopsies.", followUp: null, context:"Just Jeff being Jeff."},
{id: 12, quote:"Wow. What a piece of metal.", followUp: null, context:"About some pictures of handlebars that showed up in Google Image Search."},
{id: 13, quote:"Summon a new list.", followUp: "We don't have a new list. We have to go summon a new one.", context:"Tasklister, I believe, in one of its many iterations."},
{id: 14, quote:"A man is more than his clothes.", followUp: null, context:null},
{id: 15, quote:"I know each of us has desires about people.", followUp: null, context:null},
{id: 16, quote:"What the what?", followUp: null, context:"Questioning something weird that happened during lecture."},
{id: 17, quote:"I've always wanted to live in the wild.", followUp: null, context:"To Natalie, after killing a fly or mosquito with his bare hands."},
{id: 18, quote:"Ugghhh...I hate you.", followUp: null, context:"As soon as something breaks during lecture and the console blows up."},
{id: 19, quote:"Goddammit Jeffrey.", followUp: null, context:"Talking to himself during lecture?"},
{id: 20, quote:"You want to be able to upload this into your brain as fast as possible.", followUp: null, context:"Advice for learning, generally."},
{id: 21, quote:"If you save the parent, you save the children.", followUp: null, context:"On using .build with nested resources (I think)"},
{id: 22, quote:"Live every week like it's Shark Week.", followUp: "Have you ever seen 30 Rock?", context:"His response to Tracy during their last one-on-one when she asked for advice for programming post-Flatiron."},
{id: 23, quote:"I think it's a good idea to have low expectations when you code...maybe not in interviews.", followUp: null, context:"More job advice."},
{id: 24, quote:"Some of us look very confused. Either that or very sad. Do you want to talk?", followUp: null, context:"About Ember, during last week of review."},
{id: 25, quote: "Oh no!", followUp:null, context: "(in a whispery voice when something goes wrong)"}
]